### ISSUE TITLE
NRF51_DK: make_armc5 link error 

### ISSUE THREAD

**Issue by MaggieMei** [ARMmbed/oob-mbed-os-example-ble#19]
command: mbed export -m NRF51_dk -i make_armc5
command: make

log:
```
"Compile: main.cpp"
"link: BLE_BatteryLevel.elf"
'C:/Keil_v5/ARM/ARMCC\bin\fromelf' --bin --output BLE_BatteryLevel.bin BLE_BatteryLevel.elf
'C:/Keil_v5/ARM/ARMCC\bin\fromelf' --i32 --output BLE_BatteryLevel.hex BLE_BatteryLevel.elf
srec_cat .././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/sdk/softdevice/s130/hex/s130_nrf51_2.0.0_softdevice.hex  -intel BLE_BatteryL
evel.hex -intel -o BLE_BatteryLevel-combined.hex -intel --line-length=44
process_begin: CreateProcess(NULL, srec_cat .././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/sdk/softdevice/s130/hex/s130_nrf51_2.0.0_
softdevice.hex -intel BLE_BatteryLevel.hex -intel -o BLE_BatteryLevel-combined.hex -intel --line-length=44, ...) failed.
make (e=2): The system cannot find the file specified.
make[1]: *** [BLE_BatteryLevel-combined.hex] Error 2
```

**Comment by 0xc0170** [comment]
Note: Should be fixed for RC4

```
"link: BLE_BatteryLevel.elf"
'C:/Keil_v5/ARM/ARMCC\bin\fromelf' --bin --output BLE_BatteryLevel.bin BLE_BatteryLevel.elf
'C:/Keil_v5/ARM/ARMCC\bin\fromelf' --i32 --output BLE_BatteryLevel.hex BLE_BatteryLevel.elf
"NOTE: the srec_cat binary is required to be present in your PATH. Please see http://srecord.sourceforge.net/ fo
nformation."
srec_cat .././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/sdk/softdevice/s130/hex/s130
.0.0_softdevice.hex  -intel BLE_BatteryLevel.hex -intel -o BLE_BatteryLevel-combined.hex -intel --line-length=44
```

**Comment by pan-** [comment]
All of the examples compile on my machine, no trouble here. 
@MaggieMei Don't forget to install srecord and makes it available in your path as indicated during the compilation: 

> NOTE: the srec_cat binary is required to be present in your PATH. Please see http://srecord.sourceforge.net/ for more information.

**Comment by ashok-rao** [comment]
RC4, issue still persists even though srec is installed and available in path.

```
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\windows\system32>cd /

C:\>cd Ashok\mbed_CLI\OoB_round4\BLE\nRF51_DK\oob-mbed-os-example-ble\BLE_HeartRate

C:\Ashok\mbed_CLI\OoB_round4\BLE\nRF51_DK\oob-mbed-os-example-ble\BLE_HeartRate>cd mbed-os

C:\Ashok\mbed_CLI\OoB_round4\BLE\nRF51_DK\oob-mbed-os-example-ble\BLE_HeartRate\mbed-os>mbed update mbed-os-5.2.0-rc4
[mbed] Updating library "mbed-os" to branch mbed-os-5.2.0-rc4

C:\Ashok\mbed_CLI\OoB_round4\BLE\nRF51_DK\oob-mbed-os-example-ble\BLE_HeartRate\mbed-os>cd..
```
```
|- BLE_GAPButton\shields\TARGET_ST_BLUENRG (a5d5d0b55839)
|- BLE_HeartRate\mbed-os (1d875083b701)
|- BLE_HeartRate\shields\TARGET_ST_BLUENRG (a5d5d0b55839)
|- BLE_LEDBlinker\mbed-os (1d875083b701)
```
$> mbed export -i make_armc5 -m nrf51_dk
$> make clean
$> make

![srec_nrf51_dk_makearmc5](https://cloud.githubusercontent.com/assets/17567812/19594466/14941c7a-977d-11e6-9e32-81f2e091bbd3.jpg)

```
"Compile: us_ticker.c"
"Compile: main.cpp"
"link: BLE_HeartRate.elf"
'C:/Keil_v5/ARM/ARMCC\bin\fromelf' --bin --output BLE_HeartRate.bin BLE_HeartRate.elf
'C:/Keil_v5/ARM/ARMCC\bin\fromelf' --i32 --output BLE_HeartRate.hex BLE_HeartRate.elf
"NOTE: the srec_cat binary is required to be present in your PATH. Please see http://srecord.sourceforge.net/ for more information."
srec_cat .././mbed-os/targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/sdk/softdevice/s130/hex/s130_nrf51_2.0.0_softdevice.hex  -intel BLE_HeartRate.hex -intel -o BLE_HeartRate-combined.hex -intel --line-length=44

C:\Ashok\mbed_CLI\OoB_round4\BLE\nRF51_DK\oob-mbed-os-example-ble\BLE_HeartRate>

```

**Comment by pan-** [comment]
@ashok-rao Well, did you check your ".build" folder ? 
I don't see any error here...

**Comment by ashok-rao** [comment]
@pan- .. the build directory contains the "*-combined.hex" file and flashing it to the board is OK as well (application runs fine). But what about the srec_cat error message? It's a bit misleading..

**Comment by pan-** [comment]
It is not an error, it is a note.
Testing availability of an executable on every platforms can be hard to do to avoid any issues, it was chosen to just print a note before srec_cat execution.

**Comment by ashok-rao** [comment]
OK. is it possible to add another message at the end of srec execution with the path to the final hex file? "..\.build\*-combined.hex" to confirm to the user that .hex is now ready for flashing to target?

**Comment by pan-** [comment]
It will require another change in the exporters, I guess you can add a comment in the issue: https://github.com/ARMmbed/mbed-os/issues/2962

**Comment by ashok-rao** [comment]
@pan- ..super. Thank you. I'll update.

Further to comments above, I can confirm that issue is resolved in RC4. @MaggieMei , I think you can close this issue.
